export interface IconProps {
	size?: number
}

export { default as ChevronDobleRightIcon } from './chevron-doble-right-icon'
export { default as ChevronDownIcon } from './chevron-down-icon'
export { default as CustomersIcon } from './cutomers-icon'
export { default as DeleteIcon } from './delete-icon'
export { default as DownloadIcon } from './download-icon'
export { default as EditIcon } from './edit-icon'
export { default as EyeIcon } from './eye-icon'
export { default as GalleryIcon } from './gallery-icon'
export { default as HomeIcon } from './home-icon'
export { default as MoonIcon } from './moon-icon'
export { default as PlusIcon } from './plus-icon'
export { default as PowerIcon } from './power-icon'
export { default as PrinterIcon } from './printer-icon'
export { default as ProductsIcon } from './products-icon'
export { default as QuotationIcon } from './quotation-icon'
export { default as SearchIcon } from './search-icon'
export { default as ShareIcon } from './share-icon'
export { default as SignalIcon } from './signal-icon'
export { default as StartIcon } from './start-icon'
export { default as SunIcon } from './sun-icon'
export { default as TruckIcon } from './truck-icon'
export { default as UpdateIcon } from './update-icon'
export { default as VerticalDotsIcon } from './vertical-dots-icon'
export { default as XIcon } from './x-icon'
